### ISSUE TITLE
Update apache dependency

### ISSUE THREAD

**Issue by PierreRambaud** [opscode-cookbooks/passenger_apache2#49]
Hi,

Can you update apache2 dependency in metadata.rb, the version actually released is 3.0.1 and include many fixes and updates.
I can't use passenger_apache2 on Ubuntu14.04 and Wheezy.

``` ruby
# in the current metadata.rb
depends 'apache2', '~> 1.0'
```

Regards

**Comment by hlogmans** [comment]
+1, for other newbies like me:

in Berksfile add:
cookbook 'passenger_apache2', git:'https://github.com/hlogmans/passenger_apache2.git'

look in this fork for the changes that were neccesary.

and just to enforce the apache3: (in metadata.rb) 
depends 'apache2', '~> 3.0.0'

then `berks install` and `berks update`
